select
    SIM_CARDS.ID as SIM_CARD_ID,
    SIM_CARDS.PHONE_NUMBER,
    PERSONS.ID as PERSON_ID,
    PERSONS.NAME,
    PERSONS.FAMILY
from SIM_CARDS
join PERSONS
on SIM_CARDS.OWNER_ID = PERSONS.ID;


select count(*) from PERSON_SIM_CARD_VIEW
where PERSON_ID =1 ;